<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[About to begin executing Suite Default suite]]>
    </line>
    <line>
      <![CDATA[About to begin executing Test Default test]]>
    </line>
    <line>
      <![CDATA[Test Method resides in com.coinlancer.SignUp.SignUp]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="25835" started-at="2018-07-18T10:43:49Z" finished-at="2018-07-18T10:44:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25835" started-at="2018-07-18T10:43:49Z" finished-at="2018-07-18T10:44:15Z">
      <class name="com.coinlancer.SignUp.SignUp">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.coinlancer.SignUp.SignUp@56ef9176]" name="openBrowser" is-config="true" duration-ms="3857" started-at="2018-07-18T10:43:49Z" finished-at="2018-07-18T10:43:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.coinlancer.SignUp.SignUp@56ef9176]" name="beforeMethod" is-config="true" duration-ms="3" started-at="2018-07-18T10:43:53Z" finished-at="2018-07-18T10:43:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.coinlancer.SignUp.SignUp.verifyRegistration() throws java.io.IOException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@53de625d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyRegistration()[pri:0, instance:com.coinlancer.SignUp.SignUp@56ef9176]" name="verifyRegistration" duration-ms="21463" started-at="2018-07-18T10:43:54Z" finished-at="2018-07-18T10:44:15Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.commonLibraries.Common.isElementPresent(Common.java:106)
at com.coinlancer.SignUp.SignUp.verifyRegistration(SignUp.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[Test Method resides in com.coinlancer.SignUp.SignUp]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyRegistration -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.coinlancer.SignUp.SignUp@56ef9176]" name="afterMethod" is-config="true" duration-ms="63" started-at="2018-07-18T10:44:15Z" finished-at="2018-07-18T10:44:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyRegistration status=FAILURE method=SignUp.verifyRegistration()[pri:0, instance:com.coinlancer.SignUp.SignUp@56ef9176] output=Test Method resides in com.coinlancer.SignUp.SignUp]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.coinlancer.SignUp.SignUp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
